services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring_network
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:2
    container_name: influxdb_container
    restart: unless-stopped
    ports:
      - 8086:8086
    networks:
      - monitoring_network
    volumes:
      - influxdb-data-volume:/var/lib/influxdb2
      - influxdb-config-volume:/etc/influxdb2
networks:
  monitoring_network:
    driver: local
volumes:
  grafana-volume:
    driver: local
  influxdb-data-volume:
    driver: local
  influxdb-config-volume:
    driver: local
